name: Docs
on:
  push:
    branches:
      - master
jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Publish
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with: 
          branch: gh-pages
          folder: docs/public
      - name: Archive npm failure logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: npm-logs
          path: ~/.npm/_logs